name: wiimadhiit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  video_player: ^2.9.1
  infinite_carousel: ^1.1.1
  smooth_page_indicator: ^1.1.0
  camera: ^0.10.5+9
  shared_preferences: ^2.2.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  audio_session: ^0.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/wiimadhiit-w-red.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/wiimadhiit-w-red.png"
  adaptive_icon_background: "#161616"
  adaptive_icon_monochrome: "assets/icons/wiimadhiit-w-red.png"
  

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Model files
    # - assets/model/yamnet.tflite
    # - assets/model/labels.txt
    
    # Configuration files
    - assets/configs/
    
    # Icon files
    - assets/icons/
    - assets/icons/wiimadhiit-w-red.svg
    - assets/icons/wiimadhiit-w.svg
    - assets/icons/wiimadhiit-w-active.svg
    - assets/icons/wiimadhiit-w-inactive.svg
    - assets/icons/profile-active.svg
    - assets/icons/profile-inactive.svg
    - assets/icons/pk-active.svg
    - assets/icons/pk-inactive.svg
    - assets/icons/ground-active.svg
    - assets/icons/ground-inactive.svg
    - assets/icons/activity-active.svg
    - assets/icons/activity-inactive.svg
    - assets/icons/bonus-active.svg
    - assets/icons/bonus-inactive.svg
    - assets/icons/training-active.svg
    - assets/icons/training-inactive.svg
    
    # Image files
    - assets/images/
    - assets/images/avatar_default.png
    - assets/images/player_cover.png
    
    # Video files
    - assets/video/
    - assets/video/video1.mp4
    - assets/video/video2.mp4
    - assets/video/video3.mp4
    - assets/video/video_bonus1.mp4
    - assets/video/projection_tutorials_mac.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: NotoSansSC
  #     fonts:
  #       - asset: assets/fonts/NotoSansSC-Regular.otf
  #       - asset: assets/fonts/NotoSansSC-Bold.otf
  #         weight: 700
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.otf
  #       - asset: assets/fonts/NotoSansJP-Bold.otf
  #         weight: 700
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

